{
 "title": "COSMOS dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "COSMOS node metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "COSMOS node total RAM Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "cosmos_total_ram {}", "legendFormat": "Total RAM" }
   ]
  },
  {
   "title": "COSMOS head block num",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "cosmos_head_block{}" }
   ]
  },
  {
   "title": "COSMOS node DB size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cosmos_size_of_db {}", "legendFormat": "Size of DB Gb" }
   ]
  },
  {
   "title": "COSMOS node free space on disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cosmos_free_space_of_disk {}", "legendFormat": "Free space on disk Gb" }
   ]
  },
  {
   "title": "COSMOS node RAM usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "targets": [
    { "expr": "cosmos_mem_usage{}" }
   ]
  },
  {
   "title": "COSMOS average CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "cosmos_cpu_usage{}" }
   ]
  }
 ]
}